### ISSUE TITLE
[BUG] discountAmount is always 0

### ISSUE THREAD

**Issue by NusaibaNizam** [MrigankaGhosh/Tokyo-Gul#2]
![image](https://github.com/MrigankaGhosh/Tokyo-Gul/assets/53972786/3e96f062-58e4-41ee-a56c-7765de76e47e)

Here we are dividing int by an int, so the result will also be an integer.

As the calculateDiscount is always less than 100, the integer division result is 0.

![image](https://github.com/MrigankaGhosh/Tokyo-Gul/assets/53972786/eea42a34-debe-420c-a848-3e2648695a4e)
 
So no matter what the discount is always 0.

**Comment by NusaibaNizam** [comment]
This PR : https://github.com/MrigankaGhosh/Tokyo-Gul/pull/3 is a suggested fix

**Comment by MrigankaGhosh** [comment]
Nice work.
