### ISSUE TITLE
NPE migth occur

### ISSUE THREAD

**Issue by NusaibaNizam** [MrigankaGhosh/Tokyo-Gul#4]
![image](https://github.com/MrigankaGhosh/Tokyo-Gul/assets/53972786/d860f1a7-f887-472f-a496-fb1e6ab7d219)
Here item can be null

**Comment by NusaibaNizam** [comment]
We can consider this [PR](https://github.com/MrigankaGhosh/Tokyo-Gul/pull/5) as a fix.

**Comment by MrigankaGhosh** [comment]
The is officially resolved. Thank you @NusaibaNizam
